/**
 * Centralized mock data. In a real app this lives behind the backend; keeping it
 * in one file makes it obvious what to delete once services hit real endpoints.
 */
import type {
  Appraisal,
  EmployeeProfile,
  LeaveBalance,
  LeaveEmployee,
  LeaveRequest,
  Payslip,
  PersonalDetails,
  SmartObjective,
  User,
} from '../types';

export const mockUser: User = {
  id: 'EMP-1024',
  userId: 'admin',
  name: 'Aarav Mehta',
  email: 'aarav.mehta@technova.com',
  designation: 'Senior Software Engineer',
  department: 'Product Engineering',
};

export const mockPersonalDetails: PersonalDetails = {
  fullName: 'Aarav Mehta',
  employeeId: 'EMP-1024',
  dateOfBirth: '12 Aug 1993',
  gender: 'Male',
  bloodGroup: 'O+',
  maritalStatus: 'Married',
  phone: '+91 98765 43210',
  personalEmail: 'aarav.m@gmail.com',
  address: '42, Lake View Residency, Bengaluru, KA 560037',
  emergencyContactName: 'Priya Mehta',
  emergencyContactPhone: '+91 98765 11122',
};

/**
 * Employee profile — transcribed from the web "My Profile" panel so the mobile
 * Organization/Overview tabs show the same data. Replace with a real endpoint.
 */
export const mockEmployeeProfile: EmployeeProfile = {
  header: {
    fullName: 'Baljinder Singh Dhanoa',
    designation: 'Senior IT Manager',
    phone: '9988776655',
    email: 'Jane.Smith@Company.Com',
    location: 'Sultanate of Oman',
  },
  organization: {
    division: 'Overheads',
    branch: 'OIT00000',
    department: 'OIT00000',
    section: 'Not Applicable',
    jobType: 'NA',
    designation: 'Senior IT Manager',
    grade: 'H04',
    location: 'Sultanate of Oman',
    joinedDate: '17/05/2006',
    servicePeriod: '20 Years, 1 Months & 6 Days',
    expatriate: true,
    reportsTo: 'Moh Rizwan Ali Ansari',
    role: 'Staff',
  },
  overview: {
    references: [
      {
        id: 'REF-1',
        name: 'Test',
        designation: '-',
        phoneNo: '12121212',
        email: 'Pna@gmail.com',
        organisation: '-',
        address: 'Blr',
      },
      {
        id: 'REF-2',
        name: 'As Applicable',
        designation: 'N/A',
        phoneNo: '123456789',
        email: 'test@mail.com',
        organisation: 'Finance',
        address: 'Wadi Kabir',
      },
      {
        id: 'REF-3',
        name: 'Test',
        designation: '-',
        phoneNo: '12121212',
        email: 'Pna@gmail.com',
        organisation: '-',
        address: 'Blr',
      },
    ],
    addresses: [
      {
        kind: 'Permanent',
        contactName: 'Robert Smith',
        city: 'Muttrah',
        country: '-',
        address: '456 Park Avenue',
        region: 'Muscat',
        addressType: 'Permanent',
        addressNature: '-',
      },
      {
        kind: 'Local',
        contactName: '-',
        city: '-',
        country: '-',
        address: 'Flat No 74, Air Borne Bldg, Ghala',
        region: '-',
        addressType: 'Local',
        addressNature: 'GEN',
      },
      {
        kind: 'Temporary',
        contactName: '-',
        city: '-',
        country: '-',
        address: 'Flat No 76 Temp, Air Borne Bldg, Ghala2',
        region: '-',
        addressType: 'Temporary',
        addressNature: 'ICE',
      },
      {
        kind: 'Emergency 1',
        contactName: 'Robert Smith',
        city: '-',
        country: '-',
        address: 'Flat No 84 Temp, ICE, Ghala2',
        region: '-',
        addressType: 'Emergency',
        addressNature: 'ICE',
      },
      {
        kind: 'Emergency 2',
        contactName: '-',
        city: '-',
        country: '-',
        address: 'Flat No 85, ICE, Ghala2',
        region: '-',
        addressType: 'Emergency',
        addressNature: 'ICE',
      },
    ],
  },
  generalInfo: {
    workExperience: [
      {
        id: 'WX-1',
        fromDate: '21/04/2020',
        toDate: '21/04/2025',
        designation: 'Manager',
        company: 'ABC Pvt Ltd, Mumbai',
        experience: '5 Years 1 Days',
        hasAttachment: true,
      },
    ],
    qualifications: [
      {
        id: 'QL-1',
        year: '2018',
        degree: 'Bachelor of Engg',
        specialization: 'Mechanical',
        university: 'Reva University',
        location: 'Bangalore',
        highestDegree: false,
        hasAttachment: true,
      },
      {
        id: 'QL-2',
        year: '2006',
        degree: 'Bachelor of Engg',
        specialization: 'Chemical',
        university: 'Mumbai University',
        location: 'Mumbai',
        highestDegree: false,
        hasAttachment: true,
      },
      {
        id: 'QL-3',
        year: '2006',
        degree: 'Bachelor of Engg',
        specialization: 'Chemical',
        university: 'Mumbai University',
        location: 'Mumbai',
        highestDegree: false,
        hasAttachment: true,
      },
    ],
  },
  contract: {
    category: '-',
    lastPaidDate: '31/07/2024',
    workingPattern: 'Head Office Pattern',
    otEligible: false,
    currency: 'Rial Omani',
    salary: 'Default Salary',
    contractType: 'Temporary Contract',
    contractPeriod: '22 Months',
    contractExpiryDate: '10/12/2027',
    noticePeriodDays: '30',
    probationApplicable: false,
    probationPeriod: '-',
    probationEndDate: '-',
    leaveEligible: true,
    passageApplicable: true,
    passageFrequency: '12 Days',
    sectorPassage: 'Tehran',
    ssnNo: '-',
    ssnDeduction: 'PASI',
    gratuity: 'Gratuity',
  },
  payment: {
    paymentMethod: 'Bank',
    paymentType: 'Monthly',
    primaryAccount: {
      payeeName: 'qwertyuiohgfd',
      bankName: 'Muzn Islamic Banking',
      branchName: 'HO',
      accountNumber: '234567890',
    },
    secondaryAccount: {
      payeeName: 'wertylkjhgfds',
      bankName: 'Muzn Islamic Banking',
      branchName: 'HO',
      accountNumber: '123456789',
    },
  },
  dependants: [
    {
      id: 'DEP-1',
      name: 'Gill Sandeep Kaur',
      relation: 'Wife',
      dateOfBirth: '21/09/1979',
      age: '46 Years, 9 Months & 4 Days',
      gender: 'Female',
      bloodGroup: 'N/A',
      visa: false,
      tickets: false,
      passage: 'Not Applicable',
      passageFrequency: '0 Days',
      nationality: 'N/A',
      occupation: 'N/A',
    },
    {
      id: 'DEP-2',
      name: 'Gurjap Singh',
      relation: 'Son',
      dateOfBirth: '17/02/2009',
      age: '17 Years, 4 Months & 8 Days',
      gender: 'Male',
      bloodGroup: 'N/A',
      visa: false,
      tickets: false,
      passage: 'Not Applicable',
      passageFrequency: '0 Days',
      nationality: 'N/A',
      occupation: 'N/A',
    },
    {
      id: 'DEP-3',
      name: 'Ekampreet Kaur Dhanoa',
      relation: 'Daughter',
      dateOfBirth: '30/09/2013',
      age: '12 Years, 8 Months & 26 Days',
      gender: 'Female',
      bloodGroup: 'A Positive',
      visa: true,
      tickets: false,
      passage: 'Not Applicable',
      passageFrequency: '0 Days',
      nationality: 'Omani',
      occupation: 'Retired',
    },
  ],
  documents: {
    myDocuments: [],
    dependentDocuments: [
      {
        id: 'DOC-1',
        type: 'Passport',
        holderName: 'Gill Sandeep Kaur',
        relation: 'Wife',
        issuePlace: 'Chandigarh',
        issueDate: '05/02/2015',
        expiryDate: '04/02/2025',
      },
      {
        id: 'DOC-2',
        type: 'Passport',
        holderName: 'Gurjap Singh',
        relation: 'Son',
        issuePlace: 'Muscat',
        issueDate: '11/10/2018',
        expiryDate: '10/10/2023',
      },
      {
        id: 'DOC-3',
        type: 'Passport',
        holderName: 'Ekampreet Kaur Dhanoa',
        relation: 'Daughter',
        issuePlace: 'Muscat',
        issueDate: '11/10/2018',
        expiryDate: '10/10/2023',
      },
      {
        id: 'DOC-4',
        type: 'Resident Card',
        holderName: 'Gurjap Singh',
        relation: 'Son',
        issuePlace: 'Muscat',
        issueDate: '11/04/2021',
        expiryDate: '10/04/2023',
      },
      {
        id: 'DOC-5',
        type: 'Visa',
        holderName: 'Gurjap Singh',
        relation: 'Son',
        issuePlace: 'Muscat',
        issueDate: '11/04/2021',
        expiryDate: '10/04/2023',
      },
      {
        id: 'DOC-6',
        type: 'Visa',
        holderName: 'Gill Sandeep Kaur',
        relation: 'Wife',
        issuePlace: 'Muscat',
        issueDate: '08/01/2022',
        expiryDate: '24/01/2024',
      },
      {
        id: 'DOC-7',
        type: 'Visa',
        holderName: 'Ekampreet Kaur Dhanoa',
        relation: 'Daughter',
        issuePlace: 'Muscat',
        issueDate: '08/01/2022',
        expiryDate: '29/01/2024',
      },
    ],
  },
  salary: {
    // Mirrors the web Salary Details columns; seeded from the latest pay structure.
    summary: [
      {
        id: 'SAL-1',
        name: 'Basic',
        basis: 'Monthly',
        percentage: '-',
        effStartDate: '01/08/2024',
        effEndDate: '-',
        earnings: 1450.5,
        deductions: 0,
      },
      {
        id: 'SAL-2',
        name: 'House Rental Allowance',
        basis: 'Monthly',
        percentage: '-',
        effStartDate: '01/01/2023',
        effEndDate: '-',
        earnings: 600,
        deductions: 0,
      },
      {
        id: 'SAL-3',
        name: 'Transport Allowance',
        basis: 'Monthly',
        percentage: '-',
        effStartDate: '01/12/2018',
        effEndDate: '-',
        earnings: 175,
        deductions: 0,
      },
      {
        id: 'SAL-4',
        name: 'PASI Deduction',
        basis: 'Monthly',
        percentage: '7%',
        effStartDate: '01/08/2024',
        effEndDate: '-',
        earnings: 0,
        deductions: 101.53,
      },
    ],
    details: [],
    netPay: 2123.97,
  },
  performance: {
    transfers: [
      {
        id: 'TRF-1',
        date: '21/07/2017',
        changes: [
          {
            attribute: 'Organization Change',
            oldValue: 'Planning-EMA00000-EMY00000-Not Applicable',
            newValue: 'Planning-EMA00000-EMQ00000-Not Applicable',
          },
          {
            attribute: 'Reporting Head',
            oldValue: 'Gopakumar Thankappan Nair.P',
            newValue: 'Guruswamy.R',
          },
          { attribute: 'Location', oldValue: 'YIB', newValue: 'QAL' },
        ],
        txnNo: '22/0002905',
        txnDate: '05/08/2017',
        notes: 'site transfer',
      },
    ],
    promotions: [
      {
        id: 'PRM-1',
        date: '01-Jan-2023',
        fromRole: 'IT Manager',
        fromGrade: 'H-5',
        toRole: 'Senior IT Manager',
        toGrade: 'H-4',
        lines: [
          { description: 'Basic', oldAmount: 1192.5, newAmount: 1300, increment: 107.5 },
          { description: 'House Rental Allowance', oldAmount: 500, newAmount: 600, increment: 100 },
        ],
        totalIncrease: 207.5,
        txnNo: '23/0002262',
        txnDate: '27/05/2023',
        notes: 'WEF 01.01.2023',
      },
      {
        id: 'PRM-2',
        date: '01-Dec-2018',
        fromRole: 'Assistant Manager',
        fromGrade: 'H-6',
        toRole: 'IT Manager',
        toGrade: 'H-5',
        lines: [
          { description: 'Basic', oldAmount: 935, newAmount: 1100, increment: 165 },
          { description: 'House Rental Allowance', oldAmount: 400, newAmount: 500, increment: 100 },
          { description: 'Electricity Allowance', oldAmount: 50, newAmount: 75, increment: 25 },
          { description: 'Transport Allowance', oldAmount: 125, newAmount: 175, increment: 50 },
        ],
        totalIncrease: 340,
        txnNo: '19/0000130',
        txnDate: '26/02/2019',
        notes: 'Promotion',
      },
    ],
    increments: [
      {
        id: 'INC-1',
        date: '01-08-2024',
        lines: [{ description: 'Basic', oldAmount: 1450.5, newAmount: 181.44, increment: -1269.06 }],
        totalIncrease: 0,
        txnNo: '-',
        txnDate: '03-03-2026',
        notes: 'Increased HANU PRABHAXARAN by % on Basic',
      },
      {
        id: 'INC-2',
        date: '01-04-2024',
        lines: [{ description: 'Basic', oldAmount: 1300, newAmount: 1450.5, increment: 150.5 }],
        totalIncrease: 150.5,
        txnNo: '24/0000019',
        txnDate: '27-07-2024',
        notes: 'wef 01.04.2024',
      },
      {
        id: 'INC-3',
        date: '01-04-2021',
        lines: [{ description: 'Basic', oldAmount: 1100, newAmount: 1192.5, increment: 92.5 }],
        totalIncrease: 92.5,
        txnNo: '21/0000050',
        txnDate: '28-08-2021',
        notes: 'ADMIN & IT REVIEW AUGUST 2021',
      },
      {
        id: 'INC-4',
        date: '01-01-2017',
        lines: [{ description: 'Basic', oldAmount: 864, newAmount: 935, increment: 71 }],
        totalIncrease: 71,
        txnNo: '17/0000009',
        txnDate: '19-02-2017',
        notes: 'ANNUAL REVIEW 2017 EXPATS BASIC - 1',
      },
      {
        id: 'INC-5',
        date: '01-01-2015',
        lines: [{ description: 'Basic', oldAmount: 800, newAmount: 864, increment: 64 }],
        totalIncrease: 64,
        txnNo: '15/0000017',
        txnDate: '24-03-2015',
        notes: 'ANNUAL REVIEW 2015 - EXPAT EMP',
      },
      {
        id: 'INC-6',
        date: '01-01-2014',
        lines: [{ description: 'Basic', oldAmount: 750, newAmount: 800, increment: 50 }],
        totalIncrease: 50,
        txnNo: '14/0000002',
        txnDate: '24-01-2014',
        notes: 'ANNUAL REVIEW - EXPATS 2014',
      },
    ],
    disciplinaryActions: [],
  },
  leavesTaken: [
    { year: '2014', days: 55, tone: 'normal' },
    { year: '2015', days: 70, tone: 'normal' },
    { year: '2016', days: 36, tone: 'normal' },
    { year: '2017', days: 29, tone: 'normal' },
    { year: '2018', days: 29, tone: 'normal' },
    { year: '2019', days: 3, tone: 'low' },
    { year: '2020', days: 10, tone: 'high' },
    { year: '2021', days: 43, tone: 'normal' },
    { year: '2022', days: 21, tone: 'normal' },
    { year: '2023', days: 4, tone: 'low' },
    { year: '2024', days: 46, tone: 'normal' },
  ],
  activeLoans: [],
  careerPlan: {
    currentRole: 'Analyst',
    stages: [
      {
        id: 'CP-1',
        title: 'Intern',
        description: 'Entry-level position to gain experience',
        nextLevelIn: '3-6 months',
        responsibilities: ['Professional experience', 'Industry exposure', 'Mentorship program'],
        current: false,
      },
      {
        id: 'CP-2',
        title: 'Analyst',
        description: 'Perform analysis and take on responsibilities',
        nextLevelIn: '1-2 years',
        responsibilities: ['On site work', 'Additional responsibilities', 'Data analysis'],
        current: true,
      },
      {
        id: 'CP-3',
        title: 'Associate',
        description: 'Independent contributor with leadership',
        nextLevelIn: '2-3 years',
        responsibilities: ['On site work', 'Leadership', 'Client interaction'],
        current: false,
      },
      {
        id: 'CP-4',
        title: 'Senior Associate',
        description: 'Senior contributor with management responsibilities',
        nextLevelIn: '3-4 years',
        responsibilities: [
          'On site management',
          'Assistance in training',
          'Developing reports',
          'Quality assurance',
        ],
        current: false,
      },
      {
        id: 'CP-5',
        title: 'Team Leader',
        description: 'Lead team operations and project delivery',
        nextLevelIn: '4-5 years',
        responsibilities: [
          'Handling multiple projects',
          'Client acquisition and management',
          'Team coordination',
        ],
        current: false,
      },
      {
        id: 'CP-6',
        title: 'Manager',
        description: 'Oversee teams and complex projects',
        nextLevelIn: '5-6 years',
        responsibilities: [
          'Manage complex projects and clients',
          'Handling multiple projects',
          'Client acquisition and management',
          'Strategic planning',
        ],
        current: false,
      },
      {
        id: 'CP-7',
        title: 'Partner',
        description: 'Lead strategic initiatives and partnerships',
        nextLevelIn: '6+ years',
        responsibilities: [
          'Strategy development',
          'Corporate governance',
          'Client acquisition and management',
          'Business development',
        ],
        current: false,
      },
    ],
  },
};

export const mockPayslips: Payslip[] = [
  { id: 'PS-2605', month: 'May 2026', grossPay: 142000, netPay: 118400, deductions: 23600, status: 'Paid' },
  { id: 'PS-2604', month: 'April 2026', grossPay: 142000, netPay: 118400, deductions: 23600, status: 'Paid' },
  { id: 'PS-2603', month: 'March 2026', grossPay: 142000, netPay: 117900, deductions: 24100, status: 'Paid' },
  { id: 'PS-2602', month: 'February 2026', grossPay: 138000, netPay: 115200, deductions: 22800, status: 'Paid' },
];

export const mockLeaveEmployee: LeaveEmployee = {
  employeeCode: '1007807',
  employeeName: 'Baljinder Singh Dhanoa',
  designation: 'Senior IT Manager',
  grade: 'H-4',
  dateOfBirth: '25/07/1978',
  age: 48,
  joinDate: '17/05/2006',
  officeEmail: 'Jane.Smith@Company.Com',
  personalEmail: 'Jane.Smith@Example.Com',
  mobileNo: '9988776655',
  reportsTo: 'Moh Rizwan Ali Ansari',
  division: 'Overheads',
  branch: 'Oit00000',
  department: 'Oit00000',
  section: 'Not Applicable',
  serviceYears: 20,
  nationality: 'Omani',
};

/** People selectable as "Person Responsible in Absence". */
export const mockColleagues: string[] = [
  'Moh Rizwan Ali Ansari',
  'Priya Mehta',
  'Aarav Mehta',
  'Sara Khan',
  'Daniel Lee',
];

export const mockLeaveBalances: LeaveBalance[] = [
  { type: 'Casual', total: 12, used: 5 },
  { type: 'Sick', total: 10, used: 2 },
  { type: 'Earned', total: 18, used: 6 },
];

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: 'LR-3012',
    type: 'Earned',
    fromDate: '18 Jun 2026',
    toDate: '20 Jun 2026',
    days: 3,
    reason: 'Family function out of town.',
    status: 'Approved',
    appliedOn: '02 Jun 2026',
  },
  {
    id: 'LR-3009',
    type: 'Sick',
    fromDate: '09 Jun 2026',
    toDate: '09 Jun 2026',
    days: 1,
    reason: 'Fever and rest advised.',
    status: 'Approved',
    appliedOn: '09 Jun 2026',
  },
  {
    id: 'LR-3015',
    type: 'Casual',
    fromDate: '28 Jun 2026',
    toDate: '28 Jun 2026',
    days: 1,
    reason: 'Personal errand.',
    status: 'Pending',
    appliedOn: '15 Jun 2026',
  },
];

export const mockObjectives: SmartObjective[] = [
  {
    id: 'OBJ-01',
    title: 'Ship the new billing module',
    description: 'Deliver invoicing v2 with automated tax computation by end of H1.',
    weightage: 35,
    progress: 80,
    status: 'In Progress',
    dueDate: '30 Jun 2026',
  },
  {
    id: 'OBJ-02',
    title: 'Reduce API p95 latency by 30%',
    description: 'Profile and optimize the three slowest service endpoints.',
    weightage: 25,
    progress: 55,
    status: 'In Progress',
    dueDate: '15 Jul 2026',
  },
  {
    id: 'OBJ-03',
    title: 'Mentor two junior engineers',
    description: 'Run weekly pairing sessions and track growth plans.',
    weightage: 20,
    progress: 100,
    status: 'Completed',
    dueDate: '31 May 2026',
  },
  {
    id: 'OBJ-04',
    title: 'Improve unit test coverage to 85%',
    description: 'Add tests across the payments and auth packages.',
    weightage: 20,
    progress: 0,
    status: 'Not Started',
    dueDate: '30 Aug 2026',
  },
];

export const mockAppraisals: Appraisal[] = [
  {
    id: 'APR-2025H2',
    cycle: 'H2 2025',
    reviewer: 'Neha Kapoor (Engineering Manager)',
    rating: 4.5,
    status: 'Finalized',
    submittedOn: '12 Jan 2026',
    summary: 'Exceeded expectations on delivery and ownership. Strong technical leadership.',
  },
  {
    id: 'APR-2025H1',
    cycle: 'H1 2025',
    reviewer: 'Neha Kapoor (Engineering Manager)',
    rating: 4.0,
    status: 'Finalized',
    submittedOn: '10 Jul 2025',
    summary: 'Consistent performer. Recommended to take on more cross-team initiatives.',
  },
  {
    id: 'APR-2026H1',
    cycle: 'H1 2026',
    reviewer: 'Neha Kapoor (Engineering Manager)',
    rating: 0,
    status: 'Draft',
    summary: 'Self-assessment pending. Review window opens 01 Jul 2026.',
  },
];
